### ISSUE TITLE
No matter what port I change nginx.conf's listen to, it still gives this same error

### ISSUE THREAD

**Issue by geoyws** [killercup/homebrew-openresty#21]
```
geoyws:weltanschauung geoyws$ sudo openresty -c $PWD/conf/nginx.conf -p $PWD
nginx: [emerg] bind() to 0.0.0.0:8888 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8888 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8888 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8888 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8888 failed (48: Address already in use)
nginx: [emerg] still could not bind()
```
Could anyone point me in the right direction?

**Comment by geoyws** [comment]
Something tells me that some processes are still running utilizing that port and they didn't end properly. So whenever I start openresty again... the ports are used.
```
geoyws:weltanschauung geoyws$ sudo pkill nginx
geoyws:weltanschauung geoyws$ ps -ax | grep nginx
  642 ??         0:00.01 nginx: master process openresty -c /Users/geoyws/documents/github/weltanschauung/conf/nginx.conf -p /Users/geoyws/documents/github/weltanschauung
 1395 ??         0:00.00 nginx: worker process
 1396 ??         0:00.00 nginx: worker process
 1397 ??         0:00.00 nginx: worker process
 1398 ??         0:00.00 nginx: worker process
  651 ttys000    0:00.21 /Applications/MacVim.app/Contents/MacOS/Vim -g -v nginx.conf
 1400 ttys001    0:00.00 grep nginx
```

**Comment by geoyws** [comment]
Maybe the old processes are still running.

**Comment by killercup** [comment]
Hi @geoyws, I have no idea. I also don't think this is the right place to ask this. Maybe try an openresty malling list? I'm sure there are lot more people who use openresty there.

**Comment by mikz** [comment]
@geoyws `killall nginx` or `killall openresty`

**Comment by velikanov** [comment]
@geoyws
![Kill all humans](https://media.licdn.com/mpr/mpr/shrinknp_800_800/p/2/005/0b3/059/36a09a3.jpg)

**Comment by velikanov** [comment]
@geoyws, but seriously you just have to try `sudo openresty` to start it, `sudo openresty -s reload` to reload it and `sudo openresty -s stop` to stop it

**Comment by geoyws** [comment]
It's alright guys, kill all openresty/nginx does it ;)

On Mon, Aug 17, 2015 at 5:38 PM, Serge Velikanov <notifications@github.com>
wrote:

> @geoyws <https://github.com/geoyws>, but seriously you just have to try sudo
> openresty to start it, sudo openresty -s reload to reload it and sudo
> openresty -s stop to stop it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/killercup/homebrew-openresty/issues/21#issuecomment-131747897>
> .
>



-- 
Regards,
George Yong
016-2228603
