### ISSUE TITLE
SHA256

### ISSUE THREAD

**Issue by DomT4** [killercup/homebrew-openresty#25]
Please update your formula to use SHA256.

We've been trying to deprecate SHA1 since [March](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Checksum_Deprecation.md), please try to watch for things like that as a tap author, we don't do it extremely often but leaving behind old checksums & syntax choices allows us to drop ancient code in the core & the end result is more pleasant for everyone. Appreciated!

```
http://openresty.org/download/ngx_openresty-1.7.10.2.tar.gz
5e8beafb7b32ba62fd34b323b2e9cf49884b4f0491fccf189f0b88b3e25dd0e4

http://openresty.org/download/ngx_openresty-1.7.4.1rc2.tar.gz
5daab35e41395fe964b10055f83b798415ca6a3d7921ba7cbaa28707aad50888
```

**Comment by killercup** [comment]
Thanks! This tap is pretty unmaintained right now. I'll add the sha265s you wrote (thanks for making it so easy!)

**Comment by killercup** [comment]
https://github.com/killercup/homebrew-openresty/commit/648712e72be33f4e5ea85b8d63e17d4ac7d0c160

**Comment by DomT4** [comment]
Thanks @killercup, appreciate the quick reply & fix there.

We try to lean jointly on tap authors & tap users to help formulae stay up-to-date with the minimum syntax requirements, but in reality it mostly falls almost 100% on tap authors 😕. We've discovered with our own taps at Homebrew far fewer people are interested in helping support them than the core blob of 3600 formulae or whatever we're up to there now.
