### ISSUE TITLE
IT DOESN"T WORK . TAKE THIS OFF

### ISSUE THREAD

**Issue by sap9433** [killercup/homebrew-openresty#27]
`fatal: repository 'https://github.com/killercup/homebrew-openrest/' not found
Error: Failure while executing: git clone https://github.com/killercup/homebrew-openrest /usr/local/Homebrew/Library/Taps/killercup/homebrew-openrest --depth=1`

Please save people's time and update in the desc that it's current doesn't work .

**Comment by killercup** [comment]
Your forgot a 'y' at the end of the URL.

Can't promise this works anyway, though, I haven' been using it myself for years. Feel free to fork it.
